spring:
  sql:
    init:
      data-locations: classpath:sql/schema.sql
  application:
    name: productcatalog
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: myGroup
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgreslearning
    username: postgreslearning
    password: postgreslearning
    driver-class-name: org.postgresql.Driver
  datasource:
    url: jdbc:postgresql://localhost:5432/postgreslearning
    username: postgreslearning
    password: postgreslearning
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


server:
  port: 8087

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
