libraries:
  nameOverride: "orderprocessing"
  fullnameOverride: "orderprocessing"
  environmentVariables:
    CUSTOM_PRE_OPTS: '--add-opens java.base/java.util=ALL-UNNAMED'
    EUREKA_CLIENT_REGISTER_WITH_EUREKA: 'false'
    EUREKA_CLIENT_FETCH_REGISTRY: 'false'
    CHECK_POSTGRES: false
    CHECK_KAFKA: false
    CHECK_RABBITMQ: false
    CHECK_REDIS: false
    CHECK_EUREKA_SERVER: false
    CHECK_REDIS_HOST: 'redis-master'
    KAFKA_PORT:  9092
    RABBIT_PORT:  15672
    REDIS_PORT:  6379
    POSTGRES_PORT:  5432
    EUREKA_PORT:  8080


  envBlock:
    - name: RABBITMQ_USERNAME
      valueFrom:
        secretKeyRef:
          name: orders
          key: RABBITMQ_USERNAME
    - name: RABBITMQ_PASSWORD
      valueFrom:
        secretKeyRef:
          name: orders
          key: RABBITMQ_PASSWORD

  envFromSecrets:
    - orders

  envFromConfigMap:
    - orders
