server:
  port: 9000

spring:
  application:
    name: ${GATEWAY_APPLICATION_NAME}
  cloud:
    gateway:
      routes:
        - id: productcatalog
          uri: ${PRODUCT_CATALOG_URI}
          predicates:
            - Path=**/productcatalog/**
          filters:
            - RewritePath=(?<prefix>.*)/productcatalog/(?<segment>.*), ${prefix}/productcatalog/${segment}

        - id: orderprocessing
          uri: ${ORDER_PROCESSING_URI}
          predicates:
            - Path=/orderprocessing/**
          filters:
            - RewritePath=/orderprocessing/(?<segment>.*), /orderprocessing/${segment}
