server:
  port: 9000

spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: productcatalog
          uri: http://localhost:8081/
          predicates:
            - Path=/api/v1.0/productcatalog/**
          filters:
            - RewritePath=(?<prefix>.*)/productcatalog/(?<segment>.*), ${prefix}/productcatalog/${segment}

        - id: orderprocessing
          uri: http://localhost:8082
          predicates:
            - Path=/orderprocessing/**
          filters:
            - RewritePath=/orderprocessing/(?<segment>.*), /orderprocessing/${segment}

