server:
  port: 8080

spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: productcatalog
          uri: http://productcatalog:8080/
          predicates:
            - Path=/productcatalog/**
          filters:
            - RewritePath=/productcatalog/(?<segment>.*), /productcatalog/${segment}

        - id: orderprocessing
          uri: http://orderprocessing:8080/
          predicates:
            - Path=/orderprocessing/**
          filters:
            - RewritePath=/orderprocessing/(?<segment>.*), /orderprocessing/${segment}

