{{- range $key, $value := .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $key }}
type: Opaque
data:
  {{- range $k, $v := $value }}
  {{ $k }}: {{ $v | b64enc }}
  {{- end }}
---
  {{- end }}
