# Default values for infrastructures.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# your override should supply an envName
envName: dev

# if set, override all Applications to use this project
projectOverride: default

default:
  project:
    roles: |
      - name: read-only
        description: Read-only privileges within project
        policies:
        - p, proj:{{ $.curProjName }}:read-only, applications, get, {{ $.curProjName }}/*, allow
      - name: ci-role
        description: Role to allow CICD pipeline to sync apps within project
        policies:
        - p, proj:{{ $.curProjName }}:ci-role, applications, sync, {{ $.curProjName }}/*, allow
    destinations: |
      - namespace: {{ $.Values.default.app.destination.namespace | required "Missing proj dest namespace"}}
        server: {{ $.Values.default.app.destination.server | required "Missing proj dest server" }}
  app:
    enableAutoSync: null
    autoSyncPrune: true
    destination:
      namespace: dev
      server: 'https://kubernetes.default.svc'
    project: null
    source:
      path: null
      repoURL: null
      targetRevision: feature/arrange-project-description

      extraSourceFields: |
        helm:
          valueFiles:
          - values-{{ $.Values.envName }}.yaml
          - values.yaml
      #  kustomize:
      #    namePrefix: prod-
    #extraFields: |
    #  Default fields you want on all applications, unless the app individually overrides

#projects:
#
#  auth:
#    description: 'auth services -- api gateway, auth'
#    sourceRepos:
#      - https://MY_APPS_REPOSITORY/auth/*
#
#  onboarding:
#    description: 'onboarding services -- user PII, etc'
#    sourceRepos:
#      - https://MY_APPS_REPOSITORY/onboarding/*

