spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID}


server:
  port: ${SERVER_PORT}

eureka:
  instance:
    prefer-ip-address: ${EUREKA_INSTANCE_PREFER_IP_ADDRESS}
  client:
    fetch-registry: ${EUREKA_CLIENT_FETCH_REGISTRY}
    register-with-eureka: ${EUREKA_CLIENT_REGISTER_WITH_EUREKA}
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
