spring:
  application:
    name: productcatalog
  rabbitmq:
    host: rabbitmq
    port: ${RABBIT_PORT:5672}
    username: guest
    password: guest
  kafka:
#    bootstrap-servers: kafka:29092
    bootstrap-servers: kafka:${KAFKA_PORT:9092}
    consumer:
      group-id: myGroup
  r2dbc:
    url: r2dbc:postgresql://localhost:${POSTGRES_PORT:5432}/postgreslearning
    username: postgreslearning
    password: postgreslearning
    driver-class-name: org.postgresql.Driver

server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: ${EUREKA_CLIENT_FETCH_REGISTRY}
    register-with-eureka: ${EUREKA_CLIENT_REGISTER_WITH_EUREKA}
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://eurekaserver:${EUREKA_PORT:8080}/eureka}
